clear all;

% exp_id = [29 32 34 35];
exp_id = 34;
sub_list = list_subjects(exp_id);
% target_cam_list = {'cam01', 'cam02', 'cam03', 'cam04', 'cam07', 'cam08'};
% target_cam_list = {'cam01', 'cam02', 'cam07', 'cam08'};
% target_cam = {'cam07', 'cam08'};

enable_visualize_heatmap = true;
enable_check_visualize_range = true;
% enable_visualize_heatmap = false;
% enable_check_visualize_range = false;
is_record_var = false;

% for sidx = 1:length(sub_list)
    sidx = 16;
    child_frame_offset = 0;
    sub_id = sub_list(sidx);
    % gather all the information for gaze data
    gaze_info = import_check_csv_eye_files_complete(sub_id, child_frame_offset, ...
        is_record_var, ...
        enable_visualize_heatmap, enable_check_visualize_range);
    
%     % gather images sizes in all cameras
%     imgsize_list = preprocess_check_image_size(sub_id, target_cam_list);
%     imgsize_list = cell2mat(imgsize_list);
    
    % output all the information in a row to be store in the excel file
    % image_size_eye_data_complete_log.xlsx
    if gaze_info.exist_child_gaze_data && gaze_info.exist_parent_gaze_data
        gaze_info_row = [ ...
            gaze_info.sub_folder_create_time gaze_info.child_csv_modify_time gaze_info.parent_csv_modify_time ...
            gaze_info.child_frame_offset_cumulative ...
            gaze_info.eye_x_max gaze_info.eye_y_max gaze_info.is_need_rescale ...
            gaze_info.child_gaze_valid_prop gaze_info.parent_gaze_valid_prop ...
            gaze_info.child_gaze_range_x gaze_info.child_gaze_range_y ...
            gaze_info.parent_gaze_range_x gaze_info.parent_gaze_range_y];
    elseif gaze_info.exist_child_gaze_data && ~gaze_info.exist_parent_gaze_data
        gaze_info_row = [ ...
            gaze_info.sub_folder_create_time gaze_info.child_csv_modify_time NaN ...
            gaze_info.child_frame_offset_cumulative ...
            gaze_info.eye_x_max gaze_info.eye_y_max gaze_info.is_need_rescale ...
            gaze_info.child_gaze_valid_prop NaN ...
            gaze_info.child_gaze_range_x gaze_info.child_gaze_range_y ...
            NaN NaN  NaN NaN];
    elseif ~gaze_info.exist_child_gaze_data && gaze_info.exist_parent_gaze_data
        gaze_info_row = [ ...
            gaze_info.sub_folder_create_time NaN gaze_info.parent_csv_modify_time ...
            NaN ...
            gaze_info.eye_x_max gaze_info.eye_y_max gaze_info.is_need_rescale ...
            NaN gaze_info.parent_gaze_valid_prop ...
            NaN NaN NaN NaN ...
            gaze_info.parent_gaze_range_x gaze_info.parent_gaze_range_y];
    elseif ~gaze_info.exist_child_gaze_data && ~gaze_info.exist_parent_gaze_data
        gaze_info_row = [ ...
            gaze_info.sub_folder_create_time NaN NaN ...
            NaN ...
            gaze_info.eye_x_max gaze_info.eye_y_max gaze_info.is_need_rescale ...
            NaN NaN ...
            NaN NaN NaN NaN ...
            NaN NaN NaN NaN];
    end
% end